### ISSUE TITLE
[Bug] Headings' text wrapping

### ISSUE THREAD

**Issue by marc-alexis-com** [AnubisNekhet/AnuPpuccin#241] opened 2023-12-06 18:46 UTC
**Describe the bug**
Headings' text wrapping doesn't work as expected, it show the markdown symbols, and the text below.

**To Reproduce**
1. Create a title h1, h2...
2. Write enough words so that the text must continue on the line below. (thus overflowing the line)
3. See error (The ## are left over it and then the text, but what we want is : ## The text)

**Screenshots**
![CleanShot 2023-12-06 at 19 36 39](https://github.com/AnubisNekhet/AnuPpuccin/assets/149798617/21402fe1-58d4-4ecc-a3a7-bc25b206227b)

What I expected (with the rest of the text next to it):
![CleanShot 2023-12-06 at 19 41 22](https://github.com/AnubisNekhet/AnuPpuccin/assets/149798617/34221de5-1b8e-441e-867f-54ccbf89c76e)

**Comment by JoelAnderson-UU** [comment] 2024-07-30 08:55
I'd like to bump this bug report, as it still isn't fixed.  It's particularly annoying because you can't actually put your cursor at the left-most position on the second line (which, as Marc Alexis points out, shouldn't really be a second line)

I love the theme, and I think that AnuPpucin is probably also getting a big boost from this: 
[Nick Milo's Custom Obsidian Theme To Feel More Reflective - YouTube](https://www.youtube.com/watch?v=lUZjpIhYOEw&t=2s)

**Comment by DudeThatsErin** [comment] 2024-08-20 03:52
<img width="682" alt="Screenshot 2024-08-19 at 10 51 57 PM" src="https://github.com/user-attachments/assets/ac56fc87-49f8-4994-bff4-aa20ecec7a57">

Works fine for me. Looks like this may be a duplicate of https://github.com/AnubisNekhet/AnuPpuccin/issues/299

**Closed as completed** 2024-10-30 16:31 UTC
Labels: bug
